name: List subtasks

on:
  push:
    branches:
      - '**'
    paths:
      - '*/subtasks.json'
  workflow_dispatch:

jobs:
  run:
    if: ${{ github.repository != 'CKEFGISC/tps-starter' }}
    uses: CKEFGISC/tps-actions/.github/workflows/list-subtasks.yml@main
