name: New problem

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'How many problems in this contest?'

jobs:
  run:
    uses: CKEFGISC/tps-actions/.github/workflows/new-problem.yml@main
    with:
      count: ${{ fromJson(github.event.inputs.count) }}
